version: 2
jobs:
  ios:
    macos:
      xcode: 10.1.0
    environment:
    - NS_SKIP_ENV_CHECK: 'true'
    steps:
    - checkout
    - run:
        name: Pre-launch iOS Simulator
        command: xcrun instruments -w "iPhone 7 (12.1)" || true
        background: true
    - restore_cache:
        name: Restore Homebrew cache
        key: homebrew-{{ .Branch }}-2019-02-22.2
    - run:
        name: Install operating system level build dependencies with homebrew
        command: |
          brew update
          brew bundle
    - save_cache:
        name: Save Homebrew cache
        key: homebrew-{{ .Branch }}-2019-02-22.2
        paths:
        - /usr/local/Homebrew
        - /usr/local/Cellar
        - ~/Library/caches/Homebrew
    - run:
        name: Install global NativeScript settings
        command: |
          mkdir -p ~/.local/share/.nativescript-cli
          cp user-settings.json ~/.local/share/.nativescript-cli
    - restore_cache:
        name: Restore Yarn cache
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
    - run: yarn
    - save_cache:
        name: Save Yarn cache
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
        paths:
        - ~/.cache/yarn
        - node_modules
    - run:
        name: Install Python `six` package
        command: pip install six
    - run:
        name: Build iOS
        command: echo yes | yarn ios
    - run:
        name: Tests
        command: yarn e2e-appium -- --runType=sim.iPhone7 --verbose=true --ignoreDeviceController=false
workflows:
  version: 2
  build:
    jobs:
    - ios








SvetoslavTsenov
keyboard_arrow_down
Updateskeyboard_arrow_down
Supportkeyboard_arrow_down

storage
JOBS
WORKFLOWS
assessment
INSIGHTS
library_add
ADD PROJECTS
group
TEAM
SETTINGS
Projects Add Projects SvetoslavTsenov/tests-app-js-circleci
Set Up Project
CircleCI helps you ship better code, faster. To kick things off, you'll need to add a config.yml file to your project, and start building. After that, we'll start a new build for you each time someone pushes a new commit.

Select from the following options to generate a sample .yml for your project.

Operating System
 Linux macOS
Language
settings Clojuresettings Elixirsettings Gosettings Gradle (Java)settings Maven (Java)settings Nodesettings PHPsettings Pythonsettings Rubysettings Scalasettings Other
Next Steps
You're almost there! We're going to walk you through setting up a configuration file, committing it, and turning on our listener so that CircleCI can test your commits.

Want to skip ahead? Jump right into our documentation, set up a .yml file, and kick off your build with the button below.

If you start building before you've added a configuration file, your project will not run. To build your project, add a .circleci/config.yml file. Add a project on CircleCI 2.0.

1.	
Create a folder named .circleci and add a fileconfig.yml (so that the filepath be in .circleci/config.yml).

2.	
Populate the config.yml with the contents of the sample .yml (shown below).


Copy To Clipboard
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
3.	
Update the sample .yml to reflect your project's configuration.

4.	
Push this change up to GitHub.

5.	
Start building! This will launch your project on CircleCI and make our webhooks listen for updates to your work.

Start building
Sample .yml File
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test